# Generated by Django 3.0 on 2020-06-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(choices=[('l', 'lenovo'), ('d', 'dell'), ('h', 'hp'), ('s', 'sony')], max_length=50)),
                ('product_cost', models.IntegerField()),
                ('product_class', models.CharField(max_length=50)),
                ('product_color', models.CharField(max_length=50)),
            ],
        ),
    ]
