# Generated by Django 3.0 on 2020-06-10 06:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_color',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('b', 'black'), ('w', 'white'), ('g', 'grey'), ('r', 'red')], max_length=50),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='product_name',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('l', 'lenovo'), ('d', 'dell'), ('h', 'hp'), ('s', 'sony')], max_length=50),
        ),
    ]
